version: "3"

services:
  php-apache:
    image: php-apache
    ports:
      - "8080:80"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'e-commerce'
      MYSQL_USER: 'toto'
      MYSQL_PASSWORD: 'toto'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes: 
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: 'toto'
      PMA_PASSWORD: 'toto'
      PMA_ARBITRARY: 1